#!/usr/bin/env node

const puppeteer = require('puppeteer')

const BASE_URL = 'http://localhost:3000'

async function runBasicTest() {
  console.log('🚀 Starting basic test...')
  
  const browser = await puppeteer.launch({
    headless: false,
    defaultViewport: { width: 1280, height: 720 },
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  })
  
  const page = await browser.newPage()
  
  // Enable console logging
  page.on('console', msg => {
    console.log(`Browser ${msg.type()}:`, msg.text())
  })
  
  try {
    console.log('📱 Navigating to homepage...')
    await page.goto(BASE_URL, { waitUntil: 'networkidle0' })
    
    // Wait for page to load
    await new Promise(resolve => setTimeout(resolve, 3000))
    
    console.log('🔍 Checking page elements...')
    
    // Check if main elements exist
    const header = await page.$('h1')
    const heroTitle = await page.$('h2')
    const textarea = await page.$('textarea')
    const pasteButton = await page.$('button')
    
    console.log('✅ Elements found:')
    console.log(`  Header: ${header ? '✅' : '❌'}`)
    console.log(`  Hero Title: ${heroTitle ? '✅' : '❌'}`)
    console.log(`  Textarea: ${textarea ? '✅' : '❌'}`)
    console.log(`  Paste Button: ${pasteButton ? '✅' : '❌'}`)
    
    // Check if QR code is generated by default
    const qrCode = await page.$('img[alt*="QR"]')
    console.log(`  QR Code: ${qrCode ? '✅' : '❌'}`)
    
    // Check textarea content
    if (textarea) {
      const textareaValue = await page.$eval('textarea', el => el.value)
      console.log(`  Textarea content: "${textareaValue}"`)
    }
    
    // Test QR code generation
    if (textarea) {
      console.log('🔲 Testing QR code generation...')
      await page.click('textarea')
      await page.keyboard.down('Control')
      await page.keyboard.press('KeyA')
      await page.keyboard.up('Control')
      await page.type('textarea', 'Test QR Code')
      
      // Wait for QR code to generate
      await new Promise(resolve => setTimeout(resolve, 2000))
      
      const newQrCode = await page.$('img[alt*="QR"]')
      console.log(`  New QR Code generated: ${newQrCode ? '✅' : '❌'}`)
    }
    
    console.log('🎉 Basic test completed successfully!')
    
  } catch (error) {
    console.error('❌ Test failed:', error.message)
  } finally {
    await browser.close()
  }
}

runBasicTest().catch(console.error)